name: itunes-portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: SourceTree-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v3
      
      - name: installer
        shell: cmd
        run: |
          curl https://product-downloads.atlassian.com/software/sourcetree/windows/ga/SourceTreeSetup-3.4.14.exe -L --output installer.exe &&^
          7z.exe x installer.exe &&^
          7z.exe x SourceTree-3.4.14-full.nupkg &&^
          dir

      - shell: cmd
        run: xcopy /H /Y /C "SourceTree.exe.Portable.cmd" "lib\net45"
        
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "lib/net45"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "lib/net45/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
